# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170805_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
