# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170806_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='push_image',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='push_style',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
