# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 09:41
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170806_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='排序')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='图片')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='lastedited_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='push_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='push_style',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='visitors',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.Comment', verbose_name='评论'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='visi_blogs',
            field=models.ManyToManyField(to='blogs.Blog', verbose_name='浏览过的博客'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, default=blogs.models.Blog.preview, max_length=240, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog', to='blogs.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=80, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visi_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visiable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2, verbose_name='对外可见'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='设备'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='博客'),
        ),
    ]
