# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20170917_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=240, verbose_name='摘要'),
        ),
    ]
