# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20171018_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
